### ISSUE TITLE
User cannot create and read the articles.

### ISSUE THREAD

**Issue by asifiqbal-ai** [seanjs-stack/seanjs#3]
If we login as a user, there is a issue. Admin is fine. 

TypeError: Cannot read property 'indexOf' of null
    at http://localhost:3000/modules/core/client/app/init.js:22:81
    at Array.forEach (native)
    at http://localhost:3000/modules/core/client/app/init.js:21:26
    at Scope.parent.$get.Scope.$broadcast (http://localhost:3000/lib/angular/angular.js:14874:28)
    at Object.transitionTo (http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:3229:24)
    at Object.go (http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:3068:21)
    at http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:4181:20
    at http://localhost:3000/lib/angular/angular.js:16399:28
    at completeOutstandingRequest (http://localhost:3000/lib/angular/angular.js:4940:10)
    at http://localhost:3000/lib/angular/angular.js:5328:7

**Comment by Massad** [comment]
Fixed the user roles on user creation from normal signup or using the social login.
To fix it on your database, just add `["user"]` to the `roles` field in the `users table` or just create a new user.
